language: android
jdk:
  - oraclejdk7
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository
before_install:
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
script:
  - ./gradlew clean assemble || ./gradlew clean assemble
